Mocking service
kubeshop/kusk-gateway pull request #223
Opened 2022-02-09 16:03 UTC by Tarick

This PR...

## Changes

Adds the initial mocking service implementation.

## Fixes

Closes #41

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-02-21 10:16 UTC, kylehodgetts commented
Some testing instructions in the PR or some docs as part of the PR would be useful to be able to test it ourselves. There's a lot here just to review

2022-02-21 13:18 UTC, Tarick commented
> Some testing instructions in the PR or some docs as part of the PR would be useful to be able to test it ourselves. There's a lot here just to review
Added to PR description.

2022-02-21 14:21 UTC, dobegor approved these changes

2022-02-21 16:00 UTC, kylehodgetts requested changes

2022-02-21 16:00 UTC, kylehodgetts commented on cmd/helper/main.go
> +// Making these global
Making what global?

2022-02-21 16:00 UTC, kylehodgetts commented on cmd/helper/main.go
> +		nodeName                                 string
This isn't passed as a flag so it can be declared on line 37 as

`nodeName, err := os.Hostname()`

2022-02-21 16:00 UTC, kylehodgetts commented on cmd/helper/main.go
> +	var err error
As per above, you can remove this and declare it on the line below

2022-02-21 16:00 UTC, kylehodgetts commented on internal/helper/httpserver/server.go
> +		MaxHeaderBytes: 1 << 20,
What's the significance of `1 << 20`? Might be worth putting this in a well named variable with a comment as it's not immediately clear why this is needed

2022-02-22 10:25 UTC, dobegor approved these changes

2022-02-22 10:55 UTC, kylehodgetts approved these changes
LGTM

2022-02-22 10:57 UTC, merged