Add build args
kubeshop/kusk-gateway pull request #336
Opened 2022-04-26 16:21 UTC by ypoplavs

This PR...

## Changes

- added arguments for Dockerfile and Makefile build. Tested the changes in CI

2022-04-27 16:43 UTC, kylehodgetts requested changes

2022-04-27 16:43 UTC, kylehodgetts commented on .github/workflows/build.yml
> +      run: make test ANALYTICS_TRACKING_ID=${{ secrets.ANALYTICS_TRACKING_ID }} ANALYTICS_API_KEY=${{ secrets.ANALYTICS_API_KEY }}
```suggestion
      run: make test TelemetryToken=${{ secrets.TELEMETRY_TOKEN }}
```

2022-04-27 16:43 UTC, kylehodgetts commented on .github/workflows/release.yaml
> +          build-args: ANALYTICS_API_KEY=${{ secrets.ANALYTICS_API_KEY }},ANALYTICS_TRACKING_ID=${{ secrets.ANALYTICS_TRACKING_ID }}
```suggestion
          build-args: TelemetryToken=${{ secrets.TELEMETRY_TOKEN }}
```

2022-04-27 16:43 UTC, kylehodgetts commented on .github/workflows/release.yaml
> +          build-args: ANALYTICS_API_KEY=${{ secrets.ANALYTICS_API_KEY }},ANALYTICS_TRACKING_ID=${{ secrets.ANALYTICS_TRACKING_ID }}
```suggestion
          build-args: TelemetryToken=${{ secrets.TELEMETRY_TOKEN }}
```

2022-04-28 00:43 UTC, jasmingacic approved these changes

2022-04-28 01:22 UTC, jasmingacic commented
Sorry for committing Kyle's suggestions but for a moment i thought it was my PR :D

2022-04-28 08:54 UTC, kylehodgetts approved these changes

2022-04-28 12:50 UTC, merged