Rename annotation to `gateway.kusk.io`
kubeshop/kusk-gateway pull request #528
Opened 2022-07-07 09:47 UTC by mbana

Use public Kubernetes annotations by having keys, e.g., (`gateway.kusk.io`), that contain periods.

Closes kubeshop/kusk#49.

See <https://github.com/kubeshop/kusk/issues/49>.

Signed-off-by: Mohamed Bana <mohamed@bana.io>

---

**Note:** kubeshop/helm-charts#200 depends on this.

---

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-07-07 11:49 UTC, aabedraba approved these changes

2022-07-07 12:03 UTC, povilasv submitted a review, later dismissed
In general LGTM, but this is a breaking change, should we support both annotations as away to not break users?

2022-07-13 09:55 UTC, jasmingacic commented
Let's put this on hold. 
Make sure we don't merge it before we look into this a bit deeper.

2022-07-13 09:56 UTC, jasmingacic requested changes
Don't merged until we talk about it

2022-07-13 10:10 UTC, sftim commented
> In general LGTM, but this is a breaking change, should we support both annotations as away to not break users?

If doing this, I'd deprecate the old way (using private annotations) and eventually drop the private annotations after waiting long enough. Also consider emitting a warning when private annotations are in use.

https://github.com/kubeshop/kusk/issues/49 suggests the annotations might be removed anyway.

2022-08-08 10:32 UTC, closed without merging